// <auto-generated />
using AspNetCoreODataSample.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AspNetCoreODataSample.Web.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("AspNetCoreODataSample.Web.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MovieID");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MovieID");

                    b.ToTable("Actor");
                });

            modelBuilder.Entity("AspNetCoreODataSample.Web.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Genre");

                    b.Property<decimal>("Price");

                    b.Property<DateTimeOffset>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("AspNetCoreODataSample.Web.Models.Actor", b =>
                {
                    b.HasOne("AspNetCoreODataSample.Web.Models.Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieID");
                });
#pragma warning restore 612, 618
        }
    }
}
